### ISSUE TITLE
70% points loss when inserting

### ISSUE THREAD

**Issue by makareth** [influxdata/influxdb-java#247] opened 2016-11-21 11:21 UTC
I wish I could populate an influxDB database with fake points. I tried to cope as much as possible with the example provided in the README.MD. As you can see, when adding  points, only 3 of them are persisted (so 70% loss).
I can achieve 100% of the samples persisted by creating a new batch for every single point, which obviously is far from efficient.

```
package com.mytest.influxdbload;

import java.io.PrintStream;
import java.util.concurrent.TimeUnit;

import org.influxdb.InfluxDB;
import org.influxdb.InfluxDB.ConsistencyLevel;
import org.influxdb.InfluxDBFactory;
import org.influxdb.dto.BatchPoints;
import org.influxdb.dto.Point;
import org.influxdb.dto.Pong;
import org.influxdb.dto.Query;
import org.influxdb.dto.QueryResult;

public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Starting InfluxDB loading..." );
        
        InfluxDB influxDB = InfluxDBFactory.connect("http://1.2.3.4:8086", "root", "root");
        String dbName = "testdb";
        influxDB.createDatabase(dbName);

        Pong response = influxDB.ping();
		System.out.println("Version: "+response.getVersion());
		
        BatchPoints batchPoints = BatchPoints
                .database(dbName)
                .tag("async", "true")
                .retentionPolicy("autogen")
                .consistency(ConsistencyLevel.ALL)
                .build();
        
		for (Integer i=0;i<10;i++)
		{
			System.out.println("Insert point #" + i);

	        Point point1 = Point.measurement("proberes")
	                            .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
	                            .addField("aa", 0L)
	                            .addField("ab", 0L)
	                            .addField("ac", 0L)
	                            .addField("ad", "42")
	                            .addField("ae", i + 5131L)
	                            .addField("af", i + 4615L)
	                            .addField("ag", 0L)
	                            .addField("ah", 0L)
	                            .addField("ai", 0L)
	                            .addField("aj", 0L)
	                            .addField("ak", 0L)
	                            .addField("al", 0L)
	                            .addField("am", 0L)
	                            .addField("an", 0L)
	                            .addField("ao", i+9746L)
	                            .addField("ap", 0L)
	                            .addField("aq", "FULLTEXTSEARCH")
	                            .addField("ar", 3L)
	                            .addField("as", 0L)
	                            .addField("at", (i%23) + 23L)
	                            .addField("au", 0L)
	                            .addField("av", 0L)
	                            .addField("aw", 0L)      	
	                            .addField("ax", 0L)		
	                            .addField("ay", 3L)		
	                            .addField("az", 12L)	
	                            .addField("ba", 3L)
	                            .addField("bb", 1L)
	                            .addField("bc", "LABELFULL ")
	                            .addField("bd", "LABEL456 ")
	                            .addField("be", "00000000001414")
	                            .addField("bf", i+1479466390020L)
	                            .addField("bg", " TEXTS")
	                            .addField("bh", "2")
	                            .addField("bi", 0L)
	                            .addField("bj", (i%5) + 229L)
	                            .addField("bk", 0L)
	                            .build();
	        batchPoints.point(point1);
	}
		
        influxDB.write(batchPoints);
        
        Query query = new Query("SELECT count(customer) FROM proberes", dbName);
        QueryResult result = influxDB.query(query);
        if(result.hasError())
        {
        	System.out.println( "Finished error" + result.getError());
        	return;
        }
        
        System.out.println( "Finished successfully <" +result.toString()+">" );
    }
}
```

The output is as below:

```
Starting InfluxDB loading...
Version: 1.1.0
Insert point #0
Insert point #1
Insert point #2
Insert point #3
Insert point #4
Insert point #5
Insert point #6
Insert point #7
Insert point #8
Insert point #9
Finished successfully <QueryResult [results=[Result [series=[Series [name=electrical, tags=null, columns=[time, count], values=[[1970-01-01T00:00:00Z, 3.0]]]], error=null]], error=null]>
```

The InfluxDB server show:
```
[httpd] 80.13.217.210 - - [21/Nov/2016:12:14:43 +0100] "GET /ping HTTP/1.1" 204 0 "-" "okhttp/3.4.1" b3d9dfe8-afdb-11e6-82a2-000000000000 56
[httpd] 80.13.217.210 - root [21/Nov/2016:12:14:43 +0100] "POST /write?consistency=all&db=testdb&p=%5BREDACTED%5D&precision=n&rp=autogen&u=root HTTP/1.1" 204 0 "-" "okhttp/3.4.1" b3e5c4c2-afdb-11e6-82a3-000000000000 20112
[query] 2016/11/21 12:14:43 SELECT count(customer) FROM testdb.autogen.proberes
[httpd] 80.13.217.210 - root [21/Nov/2016:12:14:43 +0100] "GET /query?db=testdb&p=%5BREDACTED%5D&q=SELECT+count%28ab%29+FROM+proberes&u=root HTTP/1.1" 200 123 "-" "okhttp/3.4.1" b3ebba4c-afdb-11e6-82a4-000000000000 789
```

**Comment by majst01** [comment] 2016-11-21 12:40
Hi,

please add a 

```java
influxDB.close()
```
to your code before you query the results, because otherwise batch points might not be written to influxdb.

**Comment by makareth** [comment] 2016-11-22 13:58
When looking at the interface declaration of InfluxDB, the function close() is not declared in Maven artifact influxdb-java in version 2.4. As a consequence, when building I get a "The method close() is undefined for ```
type InfluxDB". This make it not possible to close() with the following pom.xml : 
    <dependency>
      <groupId>org.influxdb</groupId>
      <artifactId>influxdb-java</artifactId>
      <version>2.4</version>
    </dependency>
```

**Comment by majst01** [comment] 2016-11-22 17:25
you are right, we are on the way to release 2.5, meanwhile try to clone this repo and compile version 2.5 by yourself. If possible please give feedback with this version.

**Comment by jiafu1115** [comment] 2016-11-22 23:17
the issue may be your time precison is low so that some data be overrided due to same time. so you just make sure you use high time pricison or using tags. it is no relationship with async or batch. you can refer to http://stackoverflow.com/questions/38850028/writing-different-measurements-points-into-influxdb-with-the-same-timestamp   wait your test cases code change and feedback.

**Comment by jiafu1115** [comment] 2016-11-22 23:21
@majst01  if the issue' root cause is my point. I think we should improve readme' demo code to avoid similar issues for new learner. WDYT？

**Comment by makareth** [comment] 2016-11-23 09:17
Built commit 5c3b2ba586d5128b2c17feb6aa6e57e0d2a615fb, and got no loss. So far, looks great. The time field of each sample are between 20 and 40 ms appart. I guess the issue here was the .close() not being closed. But @jiafu1115 I agree, this can be tricky and could be detailed (although its a very specific InfluxDB trick, not connector's).

My POM was updated as follow :
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>20.0</version>
</dependency>

<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.4.2</version>
</dependency>

<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>logging-interceptor</artifactId>
    <version>3.4.2</version>
</dependency>

<dependency>
    <groupId>com.squareup.retrofit</groupId>
    <artifactId>retrofit</artifactId>
    <version>2.0.0-beta2</version>
</dependency>

<dependency>
    <groupId>com.squareup.retrofit2</groupId>
    <artifactId>converter-moshi</artifactId>
    <version>2.1.0</version>
</dependency>

**Comment by jiafu1115** [comment] 2016-11-23 09:41
how you fix the issue？ change code ？

**Comment by jiafu1115** [comment] 2016-11-23 09:41
how you fix the issue？ change code ？

**Comment by makareth** [comment] 2016-11-23 10:30
I added, just after influxDB.write(batchPoints) the following line :
`influxDB.close();`

I used tag 5c3b2ba586d5128b2c17feb6aa6e57e0d2a615fb from master branch to build influxdb-java, and used that in my pom.xml : 
```
     <dependency>
        <groupId>org.influxdb</groupId>
        <artifactId>influxdb-java</artifactId>
        <version>2.4</version>
        <scope>system</scope>
        <systemPath>${basedir}/lib/influxdb-java-2.4-SNAPSHOT.jar</systemPath>
    </dependency>
```

My updated code looks like :

```
package com.mytest.influxdbload;

import java.io.PrintStream;
import java.util.concurrent.TimeUnit;

import org.influxdb.InfluxDB;
import org.influxdb.InfluxDB.ConsistencyLevel;
import org.influxdb.InfluxDBFactory;
import org.influxdb.dto.BatchPoints;
import org.influxdb.dto.Point;
import org.influxdb.dto.Pong;
import org.influxdb.dto.Query;
import org.influxdb.dto.QueryResult;

public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Starting InfluxDB loading..." );
        
        InfluxDB influxDB = InfluxDBFactory.connect("http://1.2.3.4:8086", "root", "root");
        String dbName = "testdb";
        influxDB.createDatabase(dbName);

        Pong response = influxDB.ping();
		System.out.println("Version: "+response.getVersion());
		
        BatchPoints batchPoints = BatchPoints
                .database(dbName)
                .tag("async", "true")
                .retentionPolicy("autogen")
                .consistency(ConsistencyLevel.ALL)
                .build();
        
		for (Integer i=0;i<10;i++)
		{
			System.out.println("Insert point #" + i);

	        Point point1 = Point.measurement("proberes")
	                            .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
	                            .addField("aa", 0L)
	                            .addField("ab", 0L)
	                            .addField("ac", 0L)
	                            .addField("ad", "42")
	                            .addField("ae", i + 5131L)
	                            .addField("af", i + 4615L)
	                            .addField("ag", 0L)
	                            .addField("ah", 0L)
	                            .addField("ai", 0L)
	                            .addField("aj", 0L)
	                            .addField("ak", 0L)
	                            .addField("al", 0L)
	                            .addField("am", 0L)
	                            .addField("an", 0L)
	                            .addField("ao", i+9746L)
	                            .addField("ap", 0L)
	                            .addField("aq", "FULLTEXTSEARCH")
	                            .addField("ar", 3L)
	                            .addField("as", 0L)
	                            .addField("at", (i%23) + 23L)
	                            .addField("au", 0L)
	                            .addField("av", 0L)
	                            .addField("aw", 0L)      	
	                            .addField("ax", 0L)		
	                            .addField("ay", 3L)		
	                            .addField("az", 12L)	
	                            .addField("ba", 3L)
	                            .addField("bb", 1L)
	                            .addField("bc", "LABELFULL ")
	                            .addField("bd", "LABEL456 ")
	                            .addField("be", "00000000001414")
	                            .addField("bf", i+1479466390020L)
	                            .addField("bg", " TEXTS")
	                            .addField("bh", "2")
	                            .addField("bi", 0L)
	                            .addField("bj", (i%5) + 229L)
	                            .addField("bk", 0L)
	                            .build();
	        batchPoints.point(point1);
	}
		
        influxDB.write(batchPoints);
        influxDB.close();

        Query query = new Query("SELECT count(customer) FROM proberes", dbName);
        QueryResult result = influxDB.query(query);
        if(result.hasError())
        {
        	System.out.println( "Finished error" + result.getError());
        	return;
        }
        
        System.out.println( "Finished successfully <" +result.toString()+">" );
    }
}
```

**Comment by jiafu1115** [comment] 2016-11-23 11:05
@makareth  can you try your test code by removing the "close" to check if the issue occur?

**Comment by makareth** [comment] 2016-11-23 11:26
@jiafu1115, removed close() and the issue doesn't occur.

**Comment by majst01** [comment] 2016-11-23 11:28
I guess this is a sign to release 2.5 now :-)

**Comment by jiafu1115** [comment] 2016-11-23 11:34
@majst01 you can ship 2.5 after the PR #249,  Thanks.

ps: I am sure it is no relation ship with close for this issue.

**Comment by jiafu1115** [comment] 2016-11-23 11:50
@majst01 you can close this issue now.

**Closed** 2016-11-23 11:54 UTC
