### ISSUE TITLE
Why client parse all number values to double?

### ISSUE THREAD

**Issue by geekMessi** [influxdata/influxdb-java#595] opened 2019-04-26 12:28 UTC
RT 
when I execute query by this client , all field values that are number values are converted to double values. 
also the count , sum result .

**Comment by geekMessi** [comment] 2019-04-26 12:36
https://github.com/square/moshi/issues/192
that may be the root reason !

**Comment by majst01** [comment] 2019-04-26 14:29
duplicate of: https://github.com/influxdata/influxdb-java/issues/440

**Closed by majst01** 2019-04-26 14:29 UTC
