### ISSUE TITLE
Get integer data from InfluxDB

### ISSUE THREAD

**Issue by aurrelhebert** [influxdata/influxdb-java#153] opened 2016-03-03 11:08 UTC
Hello,
I have a field column that I pushed on influxDB using integer type ( value = 1i ). When I query this specific column I always get a double ( 1.0 ) as a result. 
I am using this specific result : 

`
QueryResult queryResult = myInfluxDB.query(myQuery);
`

**Comment by jiafu1115** [comment] 2016-11-10 07:23
@aurrelhebert  @majst01  What's **1i**?

**Comment by aurrelhebert** [comment] 2016-11-10 08:37
Hello @jiafu1115, 
Check the [data type](https://docs.influxdata.com/influxdb/v1.0/write_protocols/line_protocol_tutorial/#data-types) documentation of InfluxDB.
When you pushed numbers on InfluxDB, they are systematically converted to "Float", if you prefer to store integer, you need to push your point by adding "i" at the end of your number.
When I query my column containing integer number with this java client, I loose the information that my number is an Integer and always get a float.

**Comment by jiafu1115** [comment] 2016-11-10 08:53
@aurrelhebert  Many thanks to you! Can you give the detailed code for how you write and how you query?

**Comment by aurrelhebert** [comment] 2016-11-10 09:03
As its indicated in my first comment, I pushed Integer value using the write protocol of Influx. When requesting Influx directly I could get Integer values but when requesting them with the java client it was only float.
The request was simply done like this with my client: 
`
Query query = new Query(queryText, dbName);
QueryResult result = influxDB.query(query);
`
As this issue is quite old,  I am not using an integer column anymore in my data base. I can re-setup a local influx, if you want more details about it.

**Comment by jiafu1115** [comment] 2016-11-10 09:10
@aurrelhebert  I will test it to avoid your effort to re-setup it. waiting for my feedback.

**Comment by aurrelhebert** [comment] 2016-11-10 09:21
Thanks

**Comment by jiafu1115** [comment] 2016-11-10 12:49
@aurrelhebert  

I figure out the root cause:

in short, it is not bug for influxdb-java. the root cause is in dependency jar: moshi.
**no matter we use gson or moshi to parse json, it both parse 1 to 1.0**. So you can 1.0.
https://github.com/square/moshi/issues/192 told us it may be standard or common issue for json parse due to we doesn't know 1 is integer or double. So we can't fix it due to gson and moshi both doesn't act as you expected. What's more, I am also surprised for this.

my test code:
 
```
    public static class JsonDemo{
        private Object integer;
        private String string;
        public Object getInteger() {
            return integer;
        }
        public void setInteger(Object integer) {
            this.integer = integer;
        }
        public String getString() {
            return string;
        }
        public void setString(String string) {
            this.string = string;
        }
        @Override
        public String toString() {
            return "JsonDemo [integer=" + integer + ", string=" + string + "]";
        }
        
        
    }
         Gson gson = new Gson();
         JsonDemo element = gson.fromJson ("{\"integer\":1,\"string\":\"my\"}", JsonDemo.class);
         System.out.println(element);

JsonDemo [integer=1.0, string=my]

            JsonDemo jsonDemo = new JsonDemo();
            jsonDemo.setInteger(1);
            jsonDemo.setString("my");
        
            Moshi moshi = new Moshi.Builder().build();
            JsonAdapter<JsonDemo> jsonAdapter = moshi.adapter(JsonDemo.class);

            String json = jsonAdapter.toJson(jsonDemo);
            System.out.println(json);
            
            //{"integer":1,"string":"my"}
            
            JsonDemo jsonDemo2 = jsonAdapter.fromJson(json);
            System.out.println(jsonDemo2);
            
            //JsonDemo [integer=1.0, string=my]] 
```

@majst01  So you can close this issue just now.

**Comment by aurrelhebert** [comment] 2016-11-10 13:21
Thanks for the investigation.

**Closed** 2016-11-10 13:22 UTC

**Comment by IronsDu** [comment] 2021-05-21 07:46
Hi, How to fix this problem by myself?
