### ISSUE TITLE
lost points when write them to influxdb from riemann 

### ISSUE THREAD

**Issue by gzll** [influxdata/influxdb-java#376] opened 2017-09-29 11:51 UTC
I use riemann, and write 505 points to influxdb in about 4s, but there always are 20-40 points lost.
I use (batch 100 1/10 (async-queue! ..... influxdb), and I change the opts or use influxdb directly, whatever I do, there are some points lost.
who knows the reasons? or could tell me how to track to find the real reason?

**Comment by majst01** [comment] 2017-09-29 12:05
Can you show the code which produces this misbehavior ? You can actually force the async writer to write all outstanding points to influxdb by calling the `flush()` method on you ```influxdb``` instance.

**Comment by gzll** [comment] 2017-09-29 12:10
![qq 20170929200947](https://user-images.githubusercontent.com/25604382/31015341-2d678c12-a552-11e7-9cdc-c34b815824f4.png)

**Comment by gzll** [comment] 2017-09-29 12:11
![qq 20170929201050](https://user-images.githubusercontent.com/25604382/31015359-560c4b12-a552-11e7-9088-e5ea8f648ea3.png)

**Comment by gzll** [comment] 2017-09-29 12:13
![qq 20170929201254](https://user-images.githubusercontent.com/25604382/31015428-9fc58c50-a552-11e7-93ad-c501b4ab34ca.png)

**Comment by majst01** [comment] 2017-09-29 15:47
OK, this is not java :-)

i don't understand anything, but surprised where influxdb-java is used.

**Comment by gzll** [comment] 2017-10-10 01:13
this is the source code of the Riemann.Influxdb which written in Clojure and is a wrapper of influxdb-java.
this is the wrapper function which generate BatchPoints, and write them into influxdb.
the Riemann source code project import [org.influxdb/influxdb-java "2.4"]. 
the Riemann.influxdb code import (org.influxdb InfluxDB InfluxDBFactory InfluxDB$ConsistencyLevel) and (org.influxdb.dto BatchPoints Point).
it convert a collection of events into influxdb's batchpoint.
```clj
(defn influxdb-deprecated
  "Returns a function which accepts an event, or sequence of events, and writes
  them to InfluxDB.
  influxdb-deprecated specifics options :
  `:tag-fields`     A set of event fields to map into InfluxDB series tags.
                    (default: `#{:host}`).
  Each event can have these keys :
  `:tag-fields`     A set of event fields to map into InfluxDB series tags..
  `:precision`       The time precision. Possibles values are `:seconds`, `:milliseconds` and `:microseconds` (default `:seconds`). The event `time` will be converted."
  [opts]
  (let [opts (merge default-opts opts)
        connection (get-client opts)]
    (fn streams
      [events]
      (let [events (->> (if (sequential? events) events (list events))
                        (keep #(event->point-9 % opts)))
            ^BatchPoints batch-point (get-batchpoint opts)
            _ (doseq [event events] (.point batch-point event))]
        (write-batch-point connection batch-point)
        batch-point))))
```
this is the writing function, which use conn.write(batchpoint).
```clj
(defn write-batch-point
  "Write to influxdb the `batch-point` using the `connection`"
  [^InfluxDB connection batch-point]
  (.write connection batch-point))
```

**Comment by majst01** [comment] 2017-10-10 10:38
We are actually on Version 2.7, soon 2.8 please try to upgrade this dependency.

**Comment by gzll** [comment] 2017-10-11 02:19
Is the update about the performance issue like what I meet?  Could the new version resolve my issue?
I couldn't get such information from the releases history.

**Comment by majst01** [comment] 2017-10-12 06:09
Yes, to be precise: https://github.com/influxdata/influxdb-java/pull/292 was merged for 2.6 which gives you the ability to flush explicitly, this is not possible before 2.6. So to get your points flushed out call InfluxDB.flush()

**Comment by mcorbin** [comment] 2017-10-16 18:49
Riemann does not use batch mode, so i don't think influxdb.flush() will solve this issue.

@gzll I'm almost sure some of your events have the same :time value. In your example, you swap the ts atom, and after that deref it. You should probably try:

```clojure
(def influx (influxdb {:host "localhost"
                       :db "riemann"
                       :precision :microseconds}))
(streams
 (where (not (service #"^riemann "))
   (let [counter (atom 0)]
     (smap
       (fn [event]
         (assoc event :time (+ 1508178754 (double (/ (swap! counter inc) 1000000)))))
       #(info %)
       influx))))
```

With this test code, everything seems to work for me. I use the swap! return value to set the time, so the time will always be unique. Could you try this ?

**Comment by majst01** [comment] 2017-10-16 20:02
Not using batch mode is horrible from a performance perspective. This is because influxdb is very bad writing point by point. If you have any chance to modify riemann  to have at least the batch mode as a feature you should try.

Using unique time-stamps is a quite common mistake, but i'm sorry i was not able to identify this as root cause by reading the riemann code. 
Thanks @mcorbin for pointing into this direction.

**Comment by mcorbin** [comment] 2017-10-16 20:37
Riemann already has batching/theadpool capabilities, for example:

```clojure
(def influx (influxdb {:host "localhost"
                       :db "riemann"
                       :precision :microseconds}))

(streams
  ;; batch 2000 events at least 1/10 sec
  (batch 2000 1/10
    ;; start a threadpool for influx
    (async-queue!
      :influx-forwarder
      {:queue-size 10000
       :core-pool-size 4
       :max-pool-size 8}
      ;; forward to the influx stream
      influx)))
```
Will asynchronously forward batch of events to InfluxDB (without using the influxdb-java BatchProcessor). But yes, i should definitely make some bench about this ;)

**Comment by fmachado** [comment] 2017-11-07 10:05
@gzll @mcorbin Are you aware about how duplicated points are handled?
https://docs.influxdata.com/influxdb/v1.3/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points

If you don't think this is the root cause for this issue, could you please enable a verbose logging by calling `.setLogLevel(LogLevel.FULL);` on InfluxDB client? Probably the output will be log so, feel free to add to a gist and link here.

**Comment by mcorbin** [comment] 2017-11-07 10:17
@fmachado yes, that's what i said in my previous comment.

The Influx client is wrapped by Clojure code, so we cannot directly call `setLogLevel` on it. What @gzll can do is to print/write to a file each events sent to the influxdb Riemann stream, so we could check the event timestamp and try to find duplicated points.

For example, if @gzll use an old Riemann client not supporting microseconds resolution, he can have duplicated points.

**Comment by gzll** [comment] 2017-11-15 08:04
@mcorbin Thank you, I will try your code, but I do not understand why you think the deref will make duplicated atom's value. I just think swap! the atom a new value, when you deref the atom, you must get the new value.

**Comment by gzll** [comment] 2017-11-17 01:04
@mcorbin the deref thing does not work, almost same result got.

**Comment by mcorbin** [comment] 2017-11-18 18:14
I am not able to reproduce your issue.

Could you use this code (of something equivalent):

``clojure
(streams
 (smap
  (fn [event]
    (spit "/etc/riemann/events.json" (str (cheshire.core/generate-string event) "\n") :append true))))
```
The smap stream will write all events into `events.json`. 
You should write all events (the 505 events) in  a file just before sending them to influxdb, and send me this file. I will try to reproduce the problem with your exact events.

**Comment by fmachado** [comment] 2019-03-05 14:54
I'm closing this issue as it cannot be reproduced. Feel free to provide a Java test case if you manage to replicate the issue reported here.

**Closed by fmachado** 2019-03-05 14:54 UTC
Labels: need-more-info
