### ISSUE TITLE
Feature Request:  support Query String Parameters

### ISSUE THREAD

**Issue by tobyfan1980** [influxdata/influxdb-java#328] opened 2017-05-31 05:44 UTC
As described in [document](https://docs.influxdata.com/influxdb/v1.2/tools/api/#query-string-parameters) ,  it would be nice to pass some query string parameters into the Query constructor. 

For example, using curl, we can do 
curl -G 'http://localhost:8086/query?db=mydb&epoch=s' --data-urlencode 'q=SELECT * FROM "cpu"'

Correspondingly, we should be able to pass "epock=s" to the Query object.

**Comment by majst01** [comment] 2017-05-31 05:52
Please check if issues are already raised for the same topic

duplicate of #274

**Closed by majst01** 2017-05-31 05:52 UTC
