### ISSUE TITLE
Fails to parse host address when running in Docker swarm environments

### ISSUE THREAD

**Issue by lindsve** [influxdata/influxdb-java#528] opened 2018-10-02 08:10 UTC
We upgraded from 2.10 to 2.13 and noticed that we could not get our application running in our docker swarm environment, because it fails when connecting to Influx:

`java.lang.IllegalArgumentException: Unable to parse url: http://swarm_influx:8086`

This works in 2.11 which uses HttpUrl to parse host names, but I see that this is changed recently to use `java.net.Uri` instead.

Docker swarm autogenerates host urls based on the scheme `<name-of-swarm-stack>_<name-of-service>` so this is out of our control unfortunately.

We have currently downgraded to 2.11

**Comment by majst01** [comment] 2018-10-02 11:35
According to: https://en.wikipedia.org/wiki/Hostname and https://www.ietf.org/rfc/rfc1912.txt underscores (_) are not allowed in hostnames.

**Comment by lindsve** [comment] 2018-10-03 06:32
I know, it's basically a PITA that docker uses this url scheme. There's a registered issue for it, so hopefully they will be more compliant in the future https://github.com/moby/moby/issues/37632

On that note, I've seen underscores in hostnames for cloud provided solutions as well, so it's seemingly not uncommon although it's not per spec.

**Comment by majst01** [comment] 2018-10-03 07:50
Yes but with this bug in the moby runtime, all Java based applications will fail, so they have to fix this, it cannot be fixed in influxdb-java.

**Closed by majst01** 2018-10-03 07:50 UTC

**Comment by fmachado** [comment] 2018-10-04 07:27
I found a workaround that may help for you: https://github.com/sitewhere/sitewhere/issues/539#issuecomment-328654010
If this works, could you please add your comments here? (I will keep this issue closed because this is **not** an influxdb-java library).

As far as I could understand, this is an old issue (2014 - github.com/docker/compose/issues/229) caused by how Docker (compose/swarm) creates a hostname.
